spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    enabled: false
  datasource:
#    url: jdbc:mysql://wemccm.cejs8lhu8vxt.us-east-2.rds.amazonaws.com:3306/wemccm?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    url : jdbc:mysql://localhost:3306/wemccm?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/wemccm?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username : root
    password : jasongx89O228
#    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    # driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000 
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
mybatis:
  mapperLocations: classpath:/wemccm/src/main/java/com/wemccm/demo/dao/xml/*.xml
  typeAliasesPackage: cn.boot.domain
logging:
  level:
    root: info
# pagehelper   
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql